#!/usr/bin/env bash
# Grafana Kiosk module
# Sets up grafana-kiosk to run automatically on boot
# Written by Grant Emsley <grant@emsley.ca>
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

unpack /filesystem/home/pi /home/"${BASE_USER}" "${BASE_USER}"
#unpack /filesystem/home/root /root root
unpack /filesystem/boot /boot
unpack /filesystem/root /

if [ "$GRAFANAKIOSKOS_SPLASHSCREEN" == "yes" ]
then
	apt-get install -y fbi
	sed -i 's/$/ logo.nologo consoleblank=0 loglevel=0 quiet/' /boot/cmdline.txt
	#echo "disable_splash=1" >> /boot/config.txt
	systemctl enable splashscreen.service
	systemctl disable getty@tty1
fi

# Install required packages
apt-get -y install chromium-browser xdotool x11-xserver-utils

# Get kiosk release
wget "$GRAFANAKIOSKOS_KIOSKRELEASE" -O /usr/local/bin/grafana-kiosk
chmod +x /usr/local/bin/grafana-kiosk

# Adjust boot settings - force HDMI on at 1920x1080, set GPU memory size, disable bluetooth.
echo "hdmi_force_hotplug=1" >> /boot/config.txt
echo "hdmi_group=1" >> /boot/config.txt
echo "hdmi_mode=16" >> /boot/config.txt
echo "gpu_mem_256=128" >> /boot/config.txt
echo "gpu_mem_512=256" >> /boot/config.txt
echo "gpu_mem_1024=384" >> /boot/config.txt
echo "dtoverlay=disable-bt" >> /boot/config.txt


