#!/usr/bin/env bash
# Button module
# Watches for a button press on GPIO16 and calls /home/pi/button.sh
# Written by Grant Emsley <grant@emsley.ca>
# GPL V3
########

source /common.sh
install_cleanup_trap

apt install -y python3 python3-rpi.gpio
unpack /filesystem/root /
systemctl enable button.service
